# Generated by Django 4.2.19 on 2025-02-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='OnlineResource/')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Online Resource',
                'verbose_name_plural': 'Online Resources',
            },
        ),
        migrations.CreateModel(
            name='UsefulProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Useful Program',
                'verbose_name_plural': 'Useful Programs',
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Video Resource',
                'verbose_name_plural': 'Video Resources',
            },
        ),
    ]
